### ISSUE TITLE
Investigate adding Prettier.js to the library

### ISSUE THREAD

**Issue by evanemolo** [voltusdev/rickshaw#6]
While Rickshaw uses JSHint for linting, the codebase suffers from a lack of enforcement regarding consistent code styling. 

To do: 
- read the Prettier docs (https://prettier.io/docs/en/install.html) and understand what it will take to:
  1. install the package
  2. run the package from the CLI
  3. have Prettier run on src files only - ignore outputted files that are compiled from the Makefile, node_modules, etc.
  4. Add a line to package.json scripts that can run from the CLI with `npm run lint:prettier`
- copy over a pretterrc file from one of the other JS projects

A couple things to note:
- Prettier should be able to run without ESLint
- Babel / ES6'ing the code is not required to run Prettier

---

Once that's in place, we can enforce it with Circle CI.

**Comment by nrlakin** [comment]
Closed #7
